// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbyxotslxzaxglitndrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpieXhvdHNseHpheGdsaXRuZHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjU1NzEsImV4cCI6MjA2NjEwMTU3MX0.3UbvYzfSSMJgPYnz_7tLNa32QuV83yYCo9l1G_Z-P6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);